/*
 * This file is part of PokéFinder
 * Copyright (C) 2017-2023 by Admiral_Fish, bumba, and EzPzStreamz
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef SEARCHER_HPP
#define SEARCHER_HPP

#include <Core/Global.hpp>
#include <mutex>
#include <vector>

enum class Method : u8;

/**
 * @brief Parent generator class that stores common attributes
 *
 * @tparam Profile Profile class that is used by the searcher
 * @tparam Filter Filter class used by the searcher
 * @tparam Result Result class that is generated by the searcher
 */
template <class Profile, class Filter, class Result>
class Searcher
{
public:
    /**
     * @brief Construct a new Searcher object
     *
     * @param method Encounter method
     * @param profile Profile Information
     * @param filter State filter
     */
    Searcher(Method method, const Profile &profile, const Filter &filter) :
        profile(profile), progress(0), tsv(profile.getTID() ^ profile.getSID()), searching(false), method(method), filter(filter)
    {
    }

    /**
     * @brief Cancels the running search
     */
    void cancelSearch()
    {
        searching = false;
    }

    /**
     * @brief Returns the progress of the running search
     *
     * @return Progress
     */
    int getProgress() const
    {
        return progress;
    }

    /**
     * @brief Returns the states of the running search
     *
     * @return Vector of computed states
     */
    std::vector<Result> getResults()
    {
        std::lock_guard<std::mutex> guard(mutex);
        auto data = std::move(results);
        return data;
    }

protected:
    Profile profile;
    std::mutex mutex;
    std::vector<Result> results;
    int progress;
    u16 tsv;
    bool searching;
    Method method;
    Filter filter;
};

#endif // SEARCHER_HPP
